S3 to DropBox file upload
patroqueeet/django-dbbackup-s3 pull request #1
Opened 2023-01-12 08:46 UTC by jerinpetergeorge

2023-01-12 15:04 UTC, patroqueeet requested changes
questions: 

- is the tarball deleted after backup?
- I'm missing the management command to run it from local projects manage.py
- how did you test, that it works? feel free to quickly drop such information into an README.txt

2023-01-12 15:04 UTC, patroqueeet commented on manage.py
> +#!/usr/bin/env python
if this is used as a lib, there is no need for a manage.py file. `dbbackup` project structure should be a good place to see it. https://github.com/Develatio/django-walletpass README.txt at the very bottom has a docker cmd to run tests/lib cmd for you

2023-01-12 15:04 UTC, patroqueeet commented on requirements.txt
> +django~=4.1.5
use setup.py for deps. see wallet pass app mentioned above for a template

2023-01-12 15:04 UTC, patroqueeet commented on requirements.txt
> +django~=4.1.5
Django is a requirement of the others, so we should be able to skip here. we are with 3.2 as of now, so please start with that version earliest.

2023-01-12 15:04 UTC, patroqueeet commented on s3_dropbox_sync/asgi.py
> +"""
can be deleted

2023-01-12 15:04 UTC, patroqueeet commented on s3_dropbox_sync/settings.py
> +"""
drop the Django defaults, only lib spec settings needed. learn here: https://github.com/jazzband/django-dbbackup/blob/master/dbbackup/settings.py

2023-01-12 15:04 UTC, patroqueeet commented on s3_dropbox_sync/urls.py
> +"""s3_dropbox_sync URL Configuration
no urls required here I assume

2023-01-12 15:04 UTC, patroqueeet commented on s3_dropbox_sync/wsgi.py
> +"""
drop that unneeded one too pls

2023-01-12 15:04 UTC, patroqueeet commented on s3_dropbox_sync/sync.py
> +    def write_to_storage(self, file, path):
where is that used?

2023-01-13 09:57 UTC, jerinpetergeorge commented on manage.py
> +#!/usr/bin/env python
There are many cookiecutter templates available to create PyPackage (see [this one](https://github.com/audreyfeldroy/cookiecutter-pypackage) and also [similar ones](https://github.com/audreyfeldroy/cookiecutter-pypackage#similar-cookiecutter-templates)).

Do you have any preferences, or shall I just start with a simple package directory style?

2023-01-13 10:06 UTC, jerinpetergeorge commented
> questions:
> 
> * is the tarball deleted after backup?
> * I'm missing the management command to run it from local projects manage.py
> * how did you test, that it works? feel free to quickly drop such information into an README.txt

____________________________
1. The file is **_not deleted explicitly_** after upload (FYI: We're using `db-backup`'s function to create the file, which is configured using `DBBACKUP_TMP_DIR` variable. The default value is `/tmp` or a similar ). So, what's your take on this? IMO, we should delete it after the uploads.
2. Yes, you're. This PR is only meant to indicate the basic sync functionality is working (ie, create backup of an S3 directory and upload to DropBox) . I hope you watched the video that I've shared, else [you can find the same here](https://app.usebubbles.com/wUz6iM3xX4mkEP1qrvJm9S/demo)
3. Please refer this [video](https://app.usebubbles.com/wUz6iM3xX4mkEP1qrvJm9S/demo)

2023-01-13 10:08 UTC, jerinpetergeorge commented on s3_dropbox_sync/sync.py
> +    def write_to_storage(self, file, path):
Good catch, will be removed.

2023-01-13 10:17 UTC, patroqueeet commented on manage.py
> +#!/usr/bin/env python
make it simple, as less as possible. no prefs if you want to pick one

2023-01-13 10:18 UTC, patroqueeet commented
> > questions:
> > 
> > * is the tarball deleted after backup?
> > * I'm missing the management command to run it from local projects manage.py
> > * how did you test, that it works? feel free to quickly drop such information into an README.txt
> 
> 1. The file is **_not deleted explicitly_** after upload (FYI: We're using `db-backup`'s function to create the file, which is configured using `DBBACKUP_TMP_DIR` variable. The default value is `/tmp` or a similar ). So, what's your take on this? IMO, we should delete it after the uploads.
> 2. Yes, you're. This PR is only meant to indicate the basic sync functionality is working (ie, create backup of an S3 directory and upload to DropBox) . I hope you watched the video that I've shared, else [you can find the same here](https://app.usebubbles.com/wUz6iM3xX4mkEP1qrvJm9S/demo)
> 3. Please refer this [video](https://app.usebubbles.com/wUz6iM3xX4mkEP1qrvJm9S/demo)

1) let's delete
2) k
3) missed the link. will check later

2023-01-14 08:52 UTC, merged